name: CI
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: 
      - 'main'
jobs:
  build:
    strategy:
      matrix:
        ghc: ['8.8', '8.10', '9.0']
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    name: Build obs-websocket using GHC ${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up GHC ${{ matrix.ghc }}
        uses: haskell-actions/setup@v2.7.1
        id: setup
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Restore cached dependencies
        uses: actions/cache/restore@v4
        id: cache
        env:
          key: ${{ matrix.os }}-ghc-${{ matrix.ghc }}-cabal-${{ matrix.cabal }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ env.key }}-plan-${{ hashFiles('**/plan.json') }}
          restore-keys: ${{ env.key }}-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: cabal v2-build all --only-dependencies

      - name: Save cached dependencies
        uses: actions/cache/save@v4
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ steps.cache.outputs.cache-primary-key }}

      - name: Build and Test
        run: |
          make all
          make test
