name: CI
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: 
      - 'main'
jobs:
  build:
    strategy:
      matrix:
        cabal: ['3.2']
        ghc: ['8.4', '8.8', '8.10', '9.0']
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    name: Build twitchapi on GHC ${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - uses: actions/cache@v3
        name: Cache
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-build-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal') }}
      - run: |
          cabal v2-update
          cabal v2-build --only-dependencies --enable-tests all
      - run: |
          cabal v2-build
          cabal v2-test
